// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKP7-IZ3C75B0mcNlC5NpdD842-oHVaTw',
    appId: '1:157682757979:web:acd8fc8a241af07f282a7e',
    messagingSenderId: '157682757979',
    projectId: 'notificaappflutter',
    authDomain: 'notificaappflutter.firebaseapp.com',
    storageBucket: 'notificaappflutter.appspot.com',
    measurementId: 'G-4ES3PZG50F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK2N9SjUV35JW7X3uaaplhpnfUWfPclYw',
    appId: '1:157682757979:android:d24eb1d81218f261282a7e',
    messagingSenderId: '157682757979',
    projectId: 'notificaappflutter',
    storageBucket: 'notificaappflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPMhxUyelp2LtJnkbPY5OE3zhiq7BRcLE',
    appId: '1:157682757979:ios:b62d8218019bbee9282a7e',
    messagingSenderId: '157682757979',
    projectId: 'notificaappflutter',
    storageBucket: 'notificaappflutter.appspot.com',
    iosClientId: '157682757979-vqu6nq0nqgqmshto6ka98ftapmm81c85.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPMhxUyelp2LtJnkbPY5OE3zhiq7BRcLE',
    appId: '1:157682757979:ios:a47094b5463d5cb1282a7e',
    messagingSenderId: '157682757979',
    projectId: 'notificaappflutter',
    storageBucket: 'notificaappflutter.appspot.com',
    iosClientId: '157682757979-mgs05orkchmf1vj33606t1jfrj5uok4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificaApp.RunnerTests',
  );
}
